console.log("Hello Winc Academy");
let name = 'Julianne';
console.log(name);
let numberNumber = 4 + 4;
console.log(numberNumber);
let stringNumber = '4' + '4';
console.log(stringNumber);
let addition = 8 + 8;
console.log(addition);
let subtraction = 8 - 6;
console.log(subtraction);
let multiplication = 8 * 8;
console.log(multiplication);
let divide = 8 / 2;
console.log(divide);
let modulus = 9 % 4;
console.log(modulus);
let age = 23;
console.log(typeof age);
let ageAsString = '23';
console.log(typeof ageAsString);
